Siddhi/dice game
geekymeeky/JS-games pull request #108
Opened 2021-07-20 15:19 UTC by siddhi-244

Fixes #72

2021-07-21 19:06 UTC, kanishkaa24 requested changes
The game is not working. Maybe there is some error with the source of html file.

2021-07-21 19:15 UTC, kanishkaa24 commented on index.html
> +            <a href="dice.html" target="_blank">
Your index file is named as dicee.html. Please correct this. Also try to make it more interactive.

2021-07-22 09:39 UTC, kanishkaa24 requested changes
The nav bar is distorted in the game window.

2021-07-22 10:18 UTC, siddhi-244 commented
> The nav bar is distorted in the game window.

Can you tell me exactly where is the problem?

2021-07-22 17:47 UTC, kanishkaa24 commented
![image](https://user-images.githubusercontent.com/71253790/126684952-d67795d5-9547-4457-bf1b-d8ab94e910c2.png)

2021-07-22 18:04 UTC, siddhi-244 commented
@kanishkaa24  now please check

2021-07-22 18:07 UTC, kanishkaa24 requested changes
![image](https://user-images.githubusercontent.com/71253790/126687536-2dd0bbea-a5c1-4843-bee8-d8366dd447ed.png)
It is still the same and your game is not working.

2021-07-23 02:42 UTC, siddhi-244 commented
@kanishkaa24  now?

2021-07-23 13:28 UTC, geekymeeky requested changes
Kindly fix this overlapping layout issue in your game.
![image](https://user-images.githubusercontent.com/66238394/126788510-dc7dbb59-cdc1-4f75-b8b8-33296a572694.png)

2021-07-23 13:29 UTC, siddhi-244 commented
> Kindly fix this overlapping layout issue in your game.
> ![image](https://user-images.githubusercontent.com/66238394/126788510-dc7dbb59-cdc1-4f75-b8b8-33296a572694.png)

I have changed the source in my js file as well as html file.

2021-07-23 13:36 UTC, siddhi-244 commented
Done

2021-07-23 13:48 UTC, geekymeeky requested changes
Player 1 wins even when Player 2 dice has a greater number.
![image](https://user-images.githubusercontent.com/66238394/126791048-aaf9bb50-e74e-422d-a01e-4b875e3ed7e2.png)

2021-07-23 13:57 UTC, siddhi-244 commented
Done

2021-07-24 18:37 UTC, geekymeeky commented
> Player 1 wins even when Player 2 dice has a greater number.
> ![image](https://user-images.githubusercontent.com/66238394/126791048-aaf9bb50-e74e-422d-a01e-4b875e3ed7e2.png)

@siddhi-244 The above issue has not been resolved yet. Kindly do it
![image](https://user-images.githubusercontent.com/66238394/126878183-ab5d8d55-4590-4795-86e3-3edd6bcfeebb.png)

2021-07-26 09:22 UTC, siddhi-244 commented
i saw the logic,it is right. i dont know what problem is occurring. will you please help me?

2021-07-26 18:35 UTC, kanishkaa24 commented
Try this:
- Create a start button. DO NOT DISPLAY THE DICE UNLESS THE START BUTTON IS CLICKED.
- Initialise both randomnumber1 and randomnumber2 from zero.
- When the start button is clicked, the on click button will call the random number generator function.
- Then you can have the comparison.
- There might be some issue with image sources so you can also use conditional statements rather than using the source (you can print the random number and check the images).
- Do not initialise the dice with 6.

2021-07-28 13:46 UTC, siddhi-244 commented
> Try this:
> 
> * Create a start button. DO NOT DISPLAY THE DICE UNLESS THE START BUTTON IS CLICKED.
> * Initialise both randomnumber1 and randomnumber2 from zero.
> * When the start button is clicked, the on click button will call the random number generator function.
> * Then you can have the comparison.
> * There might be some issue with image sources so you can also use conditional statements rather than using the source (you can print the random number and check the images).
> * Do not initialise the dice with 6.

Okayy !

2021-10-04 16:41 UTC, closed without merging