Snake Game is Added
geekymeeky/JS-games pull request #24
Opened 2021-07-10 03:46 UTC by Subhradeep10

I have added a New snake game in your repo
![image](https://user-images.githubusercontent.com/70656957/125150680-59394400-e15f-11eb-9da6-7009b58e6d3e.png)

Here's the game
![image](https://user-images.githubusercontent.com/70656957/125150690-6e15d780-e15f-11eb-9e8d-98284c4c0af2.png)

2021-07-10 08:12 UTC, geekymeeky requested changes
Kindly add the requested changes.

2021-07-10 08:12 UTC, geekymeeky commented on Snakegame/snake.js
> +const moveSound = new Audio('/assets/move/mp3');
The path should be `/assets/move.mp3`.

2021-07-10 08:12 UTC, geekymeeky commented on Snakegame/snake.js
> +    if(snake[0].x >= 18 || snake[0].x <=0 || snake[0].y >= 18 || snake[0].y <=0){
The snake bumps before it touches the right and bottom wall. 
I think changing this `if(snake[0].x >= 18 || snake[0].x <=0 || snake[0].y >= 18 || snake[0].y <=0)` to `if(snake[0].x > 19 || snake[0].x <=0 || snake[0].y > 19 || snake[0].y <=0)` will resolve the issue.

2021-07-10 08:12 UTC, geekymeeky commented on Snakegame/snake.js
> +        gameOverSound.play();
Music isn't playing.

2021-07-10 08:12 UTC, geekymeeky commented on Snakegame/snakegame.html
> +    <div class="body">
Add a button to navigate to the homepage.

2021-07-10 15:12 UTC, Subhradeep10 commented on Snakegame/snake.js
> +        gameOverSound.play();
Even am unable to fix it, Shall I remove it?

2021-07-10 15:36 UTC, geekymeeky commented on Snakegame/snake.js
> +        gameOverSound.play();
Yea sure. That would be better.

2021-07-10 15:41 UTC, Subhradeep10 commented
![image](https://user-images.githubusercontent.com/70656957/125168460-52dcb380-e1c3-11eb-8c9c-bf215f89d12b.png)

2021-07-10 17:07 UTC, geekymeeky commented
@Subhradeep10 I can't play the game. Check if whether it's working or not?

2021-07-11 02:43 UTC, Subhradeep10 commented
![image](https://user-images.githubusercontent.com/70656957/125181168-c14f5f00-e21f-11eb-8538-4eb8739c4b3e.png)

Check it now @geekymeeky 

![image](https://user-images.githubusercontent.com/70656957/125181172-d4622f00-e21f-11eb-972f-d1f893a95de3.png)

2021-07-11 03:00 UTC, geekymeeky approved these changes
Excellent work @Subhradeep10

2021-07-11 03:01 UTC, merged