Added Car_Game
geekymeeky/JS-games pull request #43
Opened 2021-07-11 06:29 UTC by thejaswin123

Fixes #40 
 
## Description
Built using HTML, CSS, and Javascript. This is a Basic Car game where the player wins if car reaches end of track without hitting on any other cars. Player can use left and right arrow keys to move the car to left and right, and up and down arrow keys to speed up and slow down. Player can start the game by pressing the Start Game button.

2021-07-11 17:19 UTC, kanishkaa24 requested changes
Kindly add the CSS and JS file to static and html file in the main directory with the game name and not index.html.

2021-07-11 17:28 UTC, thejaswin123 commented
> Kindly add the CSS and JS file to static and html file in the main directory with the game name and not index.html.

Changes done

2021-07-11 17:40 UTC, kanishkaa24 commented
> > Kindly add the CSS and JS file to static and html file in the main directory with the game name and not index.html.
> 
> Changes done

Changes that must be addressed:

- Add the HTML file in the root directory (of the repository) and CSS, JS, and assets to the ```static folder``` of the root directory. This is required to deploy to gh-pages. Do not create your own folder.
- Add a card on the homepage of the website to access this game.
- Add a navigation in your game HTML file to the homepage of the website.

2021-07-12 03:21 UTC, thejaswin123 commented
> > > Kindly add the CSS and JS file to static and html file in the main directory with the game name and not index.html.
> > 
> > 
> > Changes done
> 
> Changes that must be addressed:
> 
> * Add the HTML file in the root directory (of the repository) and CSS, JS, and assets to the `static folder` of the root directory. This is required to deploy to gh-pages. Do not create your own folder.
> * Add a card on the homepage of the website to access this game.
> * Add a navigation in your game HTML file to the homepage of the website.
> * Stash all the commits into a single commit.

Changes made

2021-07-12 18:08 UTC, kanishkaa24 requested changes

2021-07-12 18:08 UTC, kanishkaa24 commented on Car_game.html
> +    <div class="btnStart"> Start Game</div>
Add a navigation to the main homepage. The link should direct you back to the JS Games website.

2021-07-13 03:06 UTC, thejaswin123 commented on Car_game.html
> +    <div class="btnStart"> Start Game</div>
navigation bar added that redirects to JS Games website on click

2021-07-13 09:27 UTC, kanishkaa24 approved these changes

2021-07-13 09:31 UTC, kanishkaa24 approved these changes

2021-07-13 10:37 UTC, geekymeeky requested changes
It's not working. Kindly check it.

2021-07-13 10:57 UTC, thejaswin123 commented
> It's not working. Kindly check it.

Now it should work, changes are made.

2021-07-14 09:10 UTC, kanishkaa24 commented
![Screenshot (400)](https://user-images.githubusercontent.com/71253790/125596042-d4b8413b-1816-43ef-a937-f5d5d620ac91.png)
See your game is not visible on the site.

2021-07-14 09:16 UTC, thejaswin123 commented
> ![Screenshot (400)](https://user-images.githubusercontent.com/71253790/125596042-d4b8413b-1816-43ef-a937-f5d5d620ac91.png)
> See your game is not visible on the site.

how to add the card of the game?

2021-07-14 14:11 UTC, thejaswin123 commented
Added in index.html kindly please check
![Screenshot 2021-07-14 194001](https://user-images.githubusercontent.com/52855622/125636680-32a5da02-8141-41c3-93d9-28a1142a52e0.png)

2021-07-14 14:44 UTC, geekymeeky approved these changes

2021-07-14 14:46 UTC, merged