Added flip card memory game
geekymeeky/JS-games pull request #53
Opened 2021-07-11 13:24 UTC by mdinesh124

Fixes #37

**Description**

I have created a flip card memory game which has the following features :- 
- It has three levels : easy, medium, hard.
- It displays the high score stats.
- it has a timer running till we finish the game.

![Screenshot (279)](https://user-images.githubusercontent.com/79132253/125196929-49ae1e00-e279-11eb-91e8-cd5fbed48985.png)

2021-07-11 17:12 UTC, kanishkaa24 approved these changes

2021-07-11 17:17 UTC, kanishkaa24 requested changes
Kindly add the CSS and JS file to static and html file in the main directory with the game name and not index.html.

2021-07-12 13:29 UTC, mdinesh124 commented
I have resolved this by making a new pull request #65 which is merged. So, you can close this pull request.

2021-07-12 13:30 UTC, geekymeeky commented
Closed via #65

2021-07-12 13:30 UTC, closed without merging