Added hangman game
geekymeeky/JS-games pull request #58
Opened 2021-07-11 18:14 UTC by pranjay-poddar

linked issue #17

2021-07-11 18:22 UTC, kanishkaa24 approved these changes
Looks good to me!

2021-07-11 18:49 UTC, geekymeeky requested changes
You can push the required changes by committing to your PR branch.

2021-07-11 18:49 UTC, geekymeeky commented on index.html
> -        <div class="row game justify-content-left">
I think these lines have been mistakenly deleted. Kindly correct it.

2021-07-11 18:49 UTC, geekymeeky commented on index.html
> -    </div>
Some of the div tags are not closed properly. Thus causing layout issues. Kindly fix it. ![image](https://user-images.githubusercontent.com/66238394/125206723-54cb7300-e2a6-11eb-9a00-1856a22bc097.png)

2021-07-12 07:30 UTC, pranjay-poddar commented
Did all the required changes please check.

2021-07-12 18:25 UTC, geekymeeky requested changes
@pranjay-poddar It isn't working. Kindly run the changes before pushing them.
![image](https://user-images.githubusercontent.com/66238394/125336656-b1449600-e36b-11eb-80cf-3b7d12201a6e.png)

2021-07-12 18:29 UTC, pranjay-poddar commented
![image](https://user-images.githubusercontent.com/52539501/125337793-07660900-e36d-11eb-8393-f441aaaf9480.png)


its working perfectly in my local machine pls check, already checked it many times and found no errors in it.

2021-07-13 12:04 UTC, merged

2021-07-13 12:07 UTC, geekymeeky commented
Fix #17