Pingpong game
geekymeeky/JS-games pull request #77
Opened 2021-07-13 08:45 UTC by Manidipaaa

Fixes #42 

- Added Ping-pong game

![image](https://user-images.githubusercontent.com/70858710/125421025-5506060f-3900-4113-b1ce-e8081e4dc642.png)

2021-07-13 09:19 UTC, kanishkaa24 requested changes

2021-07-13 09:19 UTC, kanishkaa24 commented on pingpong.html
> +    <div class="banner">
Add a navigation to the homepage of JS Games.

2021-07-14 08:14 UTC, Manidipaaa commented on pingpong.html
> +    <div class="banner">
done

2021-07-14 08:51 UTC, geekymeeky commented
Closed via #83

2021-07-14 08:51 UTC, closed without merging