Added the 2048 Game the JS Games repo
geekymeeky/JS-games pull request #81
Opened 2021-07-13 16:15 UTC by Dhruv-194

Fixes #55 

**Changes I have made :**

- Created a new branch to add my game 
- Single commit PR
- Renamed all my files to the game's name
- Added html file to the root directory and css and js files to their respective folders in static folder 
- Added a screenshot of the game to images folder 
- Updated the index.html file by adding a card to navigate to my game 
- Created a button on my game page to return back to the JS games homepage

2021-07-14 09:15 UTC, kanishkaa24 approved these changes

2021-07-14 15:27 UTC, geekymeeky requested changes
Please make the necessary modifications, and it will be merged.

2021-07-14 15:33 UTC, Dhruv-194 commented on index.html
> +      </div>
The person who worked on ping pong game should be adding that but anyways I have edited it from side.

2021-07-15 09:57 UTC, merged

2021-07-15 09:58 UTC, geekymeeky reviewed
Good work